[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "stage-events-client"
dynamic = ["version"]
description = 'A client library for accessing Stage Events'

readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = []
authors = [
  { name = "Fabrice Brito", email = "info@terradue.com" },
  { name = "Simone Tripodi", email = "info@terradue.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "attrs==26.1.0",
  "httpx>=0.23.0,<0.29.0",
  "pydantic==2.13.4",
  "eoap-problems-registry>=1.2.0"
]

[project.optional-dependencies]
cli = [
  "click>=8.1,<9",
]

[project.scripts]
send-stage-event = "stage_events_client.cli_entrypoint:main"

[project.urls]
Documentation = "https://terradue.github.io/stage-events-client/"
Issues = "https://github.com/eoap/stage-events-client/issues"
Source = "https://github.com/eoap/stage-events-client"

[tool.hatch.version]
path = "src/stage_events_client/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/stage_events_client tests}"

[tool.coverage.run]
source_pkgs = ["stage_events_client"]
branch = true
parallel = true
omit = [
  "src/stage_events_client/__about__.py",
]

[tool.coverage.paths]
stage_events_client = ["src/stage_events_client", "*/stage_events_client/src/stage_events_client"]
tests = ["tests", "*/stage_events_client/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]


[tool.hatch.envs.test]
skip-install = false
features = ["cli"]

dependencies = [
  "coverage[toml]>=7.0",
]


[tool.hatch.envs.test.scripts]
test = "python -m unittest discover -s tests -p 'test_*.py'"
testv = "python -m unittest discover -s tests -p 'test_*.py' -v"
cov = [
  "python -m coverage run --source=src/stage_events_client -m unittest discover -s tests -p 'test_*.py'",
  "python -m coverage combine",
  "python -m coverage report",
]
test-show-setup = "python -m unittest discover -s tests -p 'test_*.py' -v"

[[tool.hatch.envs.test.matrix]]
python = ["3.10", "3.11", "3.12", "3.13", "3.14"]

[tool.hatch.envs.dev]
description = "Development environment"
dependencies = [
  "pytest>=8.0",
  "ruff",
]


[tool.hatch.envs.dev.scripts]
lint = "ruff format ."
check = "ruff check --fix"
