# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-07-17T17:13:24+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class BaseCloudEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    source: str = Field(..., pattern="^[^:]+:[^:]+:[^:]+$")
    """
    Identifies the context in which an event happened.

    Pattern is `{workflow.namespace}}:{{workflow.annotations.eoap.ogc.org/id}}:{{steps.name}}`.

    """
    subject: str = Field(..., pattern="^[^:]+:[^:]+:[^:]+$")
    """
    The subject of the event in the context of the event producer (identified by `source`).

    Pattern is `{{workflow.namespace}}:{{workflow.uid}}:{{workflow.name}}`.

    """
    partitionkey: str
    """
    A partition key for the event, typically for the purposes of defining a causal relationship/grouping between multiple events.

    _Implementors note_: set it equals to the subject by default.

    """


class BaseData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    namespace: str
    """
    The declarative region that provides a scope to the processes.
    """
    owner_id: str | None = None
    """
    The unique Owner identifier to trace the member of the subscription that owns workflow.
    """
    properties: dict[str, Any] | None = None
    """
    The properties that describe the process.
    """
    priority: str | None = None
    """
    The right to proceed before other executions.
    """


class CalendarData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    event_time: AwareDatetime
    """
    The Argo Events event time, in ISO string format.
    """
    start_time: AwareDatetime
    """
    The Start Time event, in ISO string format.
    """
    end_time: AwareDatetime
    """
    The End Time event, in ISO string format.
    """


class SubmittedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    time: AwareDatetime | None = None
    """
    The Argo Workflow submission time, in ISO string format.
    """


class DismissedStatus(Enum):
    UNKNOWN = "Unknown"
    PENDING = "Pending"
    RUNNING = "Running"
    SUCCEEDED = "Succeeded"
    FAILED = "Failed"
    ERROR = "Error"


class DismissedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    status: DismissedStatus
    time: AwareDatetime | None = None
    """
    The Argo Workflow dismission time, in ISO string format.
    """


class PreparedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    process_id: str
    """
    The unique Process identifier inside the namespace.
    """
    process_version: str | None = Field(
        None,
        pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    )
    """
    The Process version, according to the [Semantic Versioning 2.0.0](https://semver.org/) scheme.

    """
    job_id: str
    """
    The unique Job identifier inside the namespace.
    """
    inputs: dict[str, Any]
    """
    The dictionary that describes inputs identifiers with related values.
    """


class ErrorDetail(BaseModel):
    """
    An object to provide explicit details on a problem towards an API consumer.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    detail: str = Field(..., max_length=4096)
    """
    A granular description on the specific error related to a body property, query parameter, path parameters, and/or header.
    """
    pointer: str | None = Field(None, max_length=1024)
    """
    A JSON Pointer to a specific request body property that is the source of error.
    """
    parameter: str | None = Field(None, max_length=1024)
    """
    The name of the query or path parameter that is the source of error.
    """
    header: str | None = Field(None, max_length=1024)
    """
    The name of the header that is the source of error.
    """
    code: str | None = Field(None, max_length=50)
    """
    A string containing additional provider specific codes to identify the error context.
    """


class Exception(BaseModel):
    """
    The `exception` object provides detailed information about an errors that occurred during an API call execution. This problem object conforms to the [RFC9457](https://www.rfc-editor.org/info/rfc9457) (formerly [RFC7807](https://tools.ietf.org/html/rfc7807)).
    The object is extended with the following properties: - `code` - a string identifier to aid the provider team better understand the error - `errors` - and array of errors providing contextual information on the root cause of the problem
    The `exception` referenced by this domain utilize a custom Terradue Problems Registry.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: AnyUrl
    """
    A URI reference that identifies the problem type.
    """
    status: int | None = Field(None, ge=100, le=599)
    """
    The HTTP status code generated by the origin server for this occurrence of the problem.
    """
    title: str | None = Field(None, max_length=1024)
    """
    A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.
    """
    detail: str | None = Field(None, max_length=4096)
    """
    A human-readable explanation specific to this occurrence of the problem.
    """
    instance: str | None = Field(None, max_length=1024)
    """
    A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    """
    code: str | None = Field(None, max_length=50)
    """
    An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry.
    """
    errors: list[ErrorDetail] | None = Field(None, max_length=1000)
    """
    An array of error details to accompany a problem details response.
    """


class Point(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["Point"] = "Point"
    coordinates: list[float] = Field(..., min_length=2)
    bbox: list[float] | None = Field(None, min_length=4)


class Coordinate(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=2)


class LineString(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["LineString"] = "LineString"
    coordinates: list[Coordinate] = Field(..., min_length=2)
    bbox: list[float] | None = Field(None, min_length=4)


class Coordinate1Item(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=2)


class Coordinate1(RootModel[list[Coordinate1Item]]):
    root: list[Coordinate1Item] = Field(..., min_length=4)


class Polygon(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["Polygon"] = "Polygon"
    coordinates: list[Coordinate1]
    bbox: list[float] | None = Field(None, min_length=4)


class Coordinate2(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=2)


class MultiPoint(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiPoint"] = "MultiPoint"
    coordinates: list[Coordinate2]
    bbox: list[float] | None = Field(None, min_length=4)


class Coordinate3Item(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=2)


class Coordinate3(RootModel[list[Coordinate3Item]]):
    root: list[Coordinate3Item] = Field(..., min_length=2)


class MultiLineString(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiLineString"] = "MultiLineString"
    coordinates: list[Coordinate3]
    bbox: list[float] | None = Field(None, min_length=4)


class Coordinate4Item(RootModel[list[float]]):
    root: list[float] = Field(..., min_length=2)


class Coordinate4(RootModel[list[Coordinate4Item]]):
    root: list[Coordinate4Item] = Field(..., min_length=4)


class MultiPolygon(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiPolygon"] = "MultiPolygon"
    coordinates: list[list[Coordinate4]]
    bbox: list[float] | None = Field(None, min_length=4)


class GeometryCollection(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["GeometryCollection"] = "GeometryCollection"
    geometries: list[
        Point | LineString | Polygon | MultiPoint | MultiLineString | MultiPolygon
    ]
    bbox: list[float] | None = Field(None, min_length=4)


class Feature(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["Feature"] = "Feature"
    id: float | str | None = None
    properties: dict[str, Any] | None
    geometry: (
        Point
        | LineString
        | Polygon
        | MultiPoint
        | MultiLineString
        | MultiPolygon
        | GeometryCollection
        | None
    )
    bbox: list[float] | None = Field(None, min_length=4)


class FeatureCollection(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["FeatureCollection"] = "FeatureCollection"
    features: list[Feature | dict[str, Any]]
    bbox: list[float] | None = Field(None, min_length=4)


class StagedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    process_id: str
    """
    The unique Process identifier inside the namespace.
    """
    process_version: str | None = Field(
        None,
        pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    )
    """
    The Process version, according to the [Semantic Versioning 2.0.0](https://semver.org/) scheme.

    """
    job_id: str
    """
    The unique Job identifier inside the namespace.
    """
    outputs: dict[str, FeatureCollection]
    """
    The dictionary that describes outputs identifiers with related STAC Item value(s).
    """


class PipedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    process_id: str
    """
    The unique Process identifier inside the namespace.
    """
    process_version: str | None = Field(
        None,
        pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    )
    """
    The Process version, according to the [Semantic Versioning 2.0.0](https://semver.org/) scheme.

    """
    job_id: str
    """
    The unique Job identifier inside the namespace.
    """
    entries: dict[str, FeatureCollection]
    """
    The dictionary that describes outputs identifiers with related STAC Item value.
    """


class ChildUsage(BaseModel):
    """
    Report of a child process execution used resources.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    name: str | None = Field(None, examples=["node_crop_6"])
    """
    The name of the child process.
    """
    start_time: AwareDatetime | None = Field(None, examples=["2025-03-11T16:20:37Z"])
    """
    The execution start time, in the date-time notation as defined by [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).

    """
    finish_time: AwareDatetime | None = Field(None, examples=["2025-03-11T16:21:25Z"])
    """
    The execution finish time, in the date-time notation as defined by [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).

    """
    elapsed_hours: float | None = Field(None, examples=[0.013333333333333334])
    """
    The execution elapsed hour(s).
    """
    elapsed_seconds: float | None = Field(None, examples=[48])
    """
    The execution elapsed second(s).
    """
    exit_code: int | None = None
    """
    The executed child process exit code.
    """
    cpus: float | None = Field(None, examples=[1])
    """
    The number of Central Processing Unit cores used for the execution.
    """
    cpu_hours: float | None = Field(None, examples=[0.013333333333333334])
    """
    The number of Central Processing Unit cores used per hour for the execution.
    """
    ram_megabytes: float | None = Field(None, examples=[536.870912])
    """
    The size of the RAM used for the execution, in MegaBytes.
    """
    ram_megabyte_hours: float | None = Field(None, examples=[7.158278826666667])
    """
    The size of the RAM used per hour for the execution, in MegaBytes.
    """
    disk_megabytes: float | None = Field(None, examples=[99.962848])
    """
    The size of the Disk used for the execution, in MegaBytes.
    """


class OrderedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    profile: str
    """
    The unique profile identifier inside the namespace.
    """
    order_id: str
    """
    The unique Order identifier inside the namespace.
    """
    entries: dict[str, FeatureCollection]
    """
    The dictionary that describes outputs identifiers with related STAC Item value.
    """


class CalendarCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["calendar-event"] = "calendar-event"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: CalendarData
    """
    The event payload.
    """


class SubmittedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["submitted"] = "submitted"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: SubmittedData
    """
    The event payload.
    """


class DismissedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["dismissed"] = "dismissed"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: DismissedData
    """
    The event payload.
    """


class PreparedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["prepared"] = "prepared"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: PreparedData
    """
    The event payload.
    """


class StagedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["staged"] = "staged"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: StagedData
    """
    The event payload.
    """


class PipedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["piped"] = "piped"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: PipedData
    """
    The event payload.
    """


class OrderedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["ordered"] = "ordered"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: OrderedData
    """
    The event payload.
    """


class Usage(BaseModel):
    """
    Report of a process total used resources.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    start_time: AwareDatetime | None = Field(None, examples=["2025-03-11T16:20:36Z"])
    """
    The execution start time, in the date-time notation as defined by [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).

    """
    finish_time: AwareDatetime | None = Field(None, examples=["2025-03-11T16:23:17Z"])
    """
    The execution finish time, in the date-time notation as defined by [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).

    """
    elapsed_hours: float | None = Field(None, examples=[0.04472222222222222])
    """
    The execution elapsed hour(s).
    """
    elapsed_seconds: int | None = Field(None, examples=[161])
    """
    The execution elapsed second(s).
    """
    cores_allowed: float | None = Field(None, examples=[8])
    """
    The maximum number of Central Processing Unit cores to use.
    """
    max_parallel_cpus: int | None = Field(None, examples=[7])
    """
    The maximum number of used Central Processing Unit cores.
    """
    total_cpu_hours: float | None = Field(None, examples=[0.21305555555555555])
    """
    The number of used Central Processing Unit cores per hour.
    """
    ram_mb_allowed: float | None = Field(None, examples=[4000])
    """
    The maximum amount of RAM to use, in MegaBytes.
    """
    total_ram_megabyte_hours: float | None = Field(None, examples=[114.3833304177778])
    """
    The total size of the RAM used per hour for the execution, in MegaBytes.
    """
    max_parallel_ram_megabytes: float | None = Field(
        None, examples=[3758.0963839999995]
    )
    total_disk_megabytes: float | None = Field(None, examples=[2490.712061999999])
    """
    The total size of the Disk used per hour for the execution, in MegaBytes.
    """
    max_parallel_tasks: int | None = None
    """
    The maximum number of parallel executing tasks.
    """
    total_tasks: int | None = Field(None, examples=[25])
    """
    The total number of executed tasks.
    """
    children: list[ChildUsage] | None = Field(
        None,
        examples=[
            [
                {
                    "cpus": 1,
                    "ram_megabytes": 536.870912,
                    "disk_megabytes": 99.962848,
                    "exit_code": 0,
                    "name": "node_crop_6",
                    "start_time": "2025-03-11T16:20:37Z",
                    "finish_time": "2025-03-11T16:21:25Z",
                    "elapsed_hours": 0.013333333333333334,
                    "elapsed_seconds": 48,
                    "ram_megabyte_hours": 7.158278826666667,
                    "cpu_hours": 0.013333333333333334,
                }
            ]
        ],
    )
    """
    The executed tasks.
    """


class CompletedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    process_id: str
    """
    The unique Process identifier inside the namespace.
    """
    process_version: str | None = Field(
        None,
        pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    )
    """
    The Process version, according to the [Semantic Versioning 2.0.0](https://semver.org/) scheme.

    """
    job_id: str
    """
    The unique Job identifier inside the namespace.
    """
    usage: Usage
    outputs: dict[str, Any]
    """
    The dictionary that describes outputs identifiers with related values.
    """


class FailedData(BaseData):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    process_id: str
    """
    The unique Process identifier inside the namespace.
    """
    process_version: str | None = Field(
        None,
        pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$",
    )
    """
    The Process version, according to the [Semantic Versioning 2.0.0](https://semver.org/) scheme.

    """
    job_id: str
    """
    The unique Job identifier inside the namespace.
    """
    exception: Exception | None = None
    usage: Usage


class CompletedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["completed"] = "completed"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: CompletedData
    """
    The event payload.
    """


class FailedCloudEvent(BaseCloudEvent):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["failed"] = "failed"
    """
    Contains a value describing the type of event related to the originating occurrence.

    """
    data: FailedData
    """
    The event payload.
    """
